server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: image-hosting
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: # Your POP3/SMTP HOST (e.g., smtp.163.com)
    port: # Your POP3/SMTP PORT (e.g., 465)
    username: # Your POP3/SMTP USERNAME
    password: # Your POP3/SMTP PASSWORD/AUTHORIZATION CODE
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: moe.imtop1.imagehosting.images.domain,moe.imtop1.imagehosting.system.domain
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: true
      logic-not-delete-value: false

sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  is-read-header: true
  is-read-param: true
  is-log: true
  jwt-secret-key: your_jwt_secret_key_here_must_be_complex

minio:
  endpoint: http://localhost:19000  # Your MinIO server endpoint
  accessKey: your_minio_access_key  # Please change it in production
  secretKey: your_minio_secret_key  # Please change it in production
  watermarkBucket: image-watermark
  originBucket: image-origin
  thumbnailBucket: image-thumbnail
  external-url: http://localhost:19000 

# 区块链系统配置（FISCO BCOS / NFT等节点适配）
blockchain:
  api-url: http://localhost:8081